
---
title: "Advanced Data Visualization with ggplot2 Extensions"
author: "Ehsan Zangene"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
# library(palmerpenguins)
# palmerpenguins::penguins
# BiocManager::install(c("ggalt", "ggbump", "ggh4x"))
library(ggalt)
library(ggbump)
library(ggh4x)
library(gghighlight)
pal <- c("Adelie" = "#FF8C00", "Gentoo" = "#159090", "Chinstrap" = "#A034F0")
```

# ggdist: Raincloud Plots

```{r raincloud}
library(ggdist)

p01 <- penguins |>
  ggplot(aes(x = species, y = bill_length_mm, fill = species)) +
  stat_halfeye(point_colour = NA, .width = 0, justification = -0.2) +
  geom_boxplot(outlier.shape = NA, alpha = 0.4, width = 0.1) +
  stat_dots(aes(colour = species), side = "left", justification = 1.1, dotsize = 0.2, binwidth =   0.4) +
  scale_fill_manual(values = pal) +
  scale_colour_manual(values = pal) +
  guides(fill = "none") +
  coord_flip()
```

# ggdist: Interval Plots

```{r interval}
p02 <- penguins |>
  drop_na(sex) |>
  ggplot(aes(x = species, y = bill_length_mm)) +
  stat_interval(.width = c(.5, .66, .95)) +
  stat_halfeye(aes(fill = sex), .width = 0, shape = 21, colour = "white", slab_alpha = .4, size = .5,
               position = position_nudge(x = .05)) +
  scale_color_viridis_d(option = "mako", direction = -1, end = .9)
```

# ggdensity: Density Plots

```{r density}
library(ggdensity)

p01 <- penguins |>
  ggplot(aes(x = body_mass_g, y = flipper_length_mm, colour = species)) +
  geom_point(alpha = .2) +
  geom_hdr_lines() +
  scale_colour_manual(values = pal)

p02 <- penguins |>
  ggplot(aes(x = body_mass_g, y = bill_depth_mm, colour = species)) +
  geom_point(alpha = .2) +
  geom_hdr_lines() +
  scale_colour_manual(values = pal)

p03 <- penguins |>
  ggplot(aes(x = body_mass_g, y = bill_length_mm, colour = species)) +
  geom_point(alpha = .2) +
  geom_hdr_lines() +
  scale_colour_manual(values = pal)
```
```{r}
p01 / p02  / p03 
# body_mass_g vs bill_length_mm
# body_mass_g vs bill_length_mm
# body_mass_g vs bill_length_mm

```

# ggridges: Ridge Plots

```{r ridge}
library(ggridges)

p1 <- penguins |>
  ggplot(aes(x = flipper_length_mm, y = species, fill = species)) +
  geom_density_ridges() +
  scale_fill_manual(values = pal) +
  scale_colour_manual(values = pal) +
  theme(legend.position = "none")

p2 <- penguins |>
  ggplot(aes(x = bill_depth_mm, y = species, fill = species)) +
  geom_density_ridges() +
  scale_fill_manual(values = pal) +
  scale_colour_manual(values = pal) +
  theme(legend.position = "none")

p3 <- penguins |>
  ggplot(aes(x = bill_length_mm, y = species, fill = species)) +
  geom_density_ridges() +
  scale_fill_manual(values = pal) +
  scale_colour_manual(values = pal) +
  theme(legend.position = "none")

p1 / p2  / p3 
```

# ggbump: Bump Charts

```{r bump}
library(ggbump)
library(lubridate)
library(janitor)

penguins_clean <- palmerpenguins::penguins_raw %>% 
  clean_names()

penguin_summary <- penguins_clean |>
  mutate(date_egg = dmy(date_egg)) |>
  filter(clutch_completion == "Yes") |>
  mutate(year = year(date_egg)) |>
  group_by(species, year) |>
  summarise(n = n(), .groups = "drop")

penguin_summary |>
  ggplot(aes(x = year, y = n, colour = species)) +
  geom_point(size = 7) +
  geom_bump() +
  geom_text(data = filter(penguin_summary, year == max(year)),
            aes(x = year + 0.1, label = species, hjust = 0), size = 5) +
  scale_x_continuous(limits = c(2007, 2009.5), breaks = 2007:2009) +
  labs(y = "Total number of complete clutches") +
  scale_fill_manual(values = pal) +
  scale_colour_manual(values = pal) +
  theme(legend.position = "none")
```



# ggh4x: Nested Facets

```{r facet}
library(ggh4x)

penguins |>
  mutate(Nester = ifelse(species == "Gentoo", "Crustaceans", "Fish & Krill")) |>
  ggplot(aes(x = culmen_length_mm, y = culmen_depth_mm, colour = species)) +
  geom_point() +
  facet_nested(~ Nester + species) +
  scale_colour_manual(values = pal) +
  theme(legend.position = "none")
```

# gghighlight: Highlighting

```{r highlight}
library(gghighlight)

penguins |>
  ggplot(aes(body_mass_g, fill = species)) +
  geom_histogram(position = "identity") +
  gghighlight() +
  scale_fill_manual(values = pal) +
  facet_wrap(~ species)
```

# patchwork and text annotation

```{r patchwork, fig.height=6, fig.width=10}
library(patchwork)
p1 <- ggplot(penguins, aes(x = culmen_length_mm, y = culmen_depth_mm)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal()

p2 <- ggplot(penguins, aes(x = culmen_length_mm, y = culmen_depth_mm, colour = species)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  scale_colour_manual(values = pal) +
  theme_minimal()

p1 + p2 + plot_layout(ncol = 2)
```



